abs(meansarray(1)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_4_patient(patnum))/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_input_match)).^2./(2*((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))^2))))
abs(meansarray(2)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_4_patient(patnum))/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_input_mismatch)).^2./(2*((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))^2))))
abs(meansarray(3)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_8_patient(patnum))/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_input_match)).^2./(2*((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))^2))))
abs(meansarray(4)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_8_patient(patnum))/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_input_mismatch)).^2./(2*((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))^2))))
abs(meansarray(5)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_16_patient(patnum))/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_input_match)).^2./(2*((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))^2))))
abs(meansarray(6)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_16_patient(patnum))/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_input_mismatch)).^2./(2*((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))^2))))

(abs(meansarray(1)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_4_patient(patnum))/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_input_match)).^2./(2*((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))^2))))+abs(meansarray(2)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_4_patient(patnum))/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_4_patient(patnum))))*mu_input_mismatch)).^2./(2*((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))^2))))+abs(meansarray(3)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_8_patient(patnum))/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_input_match)).^2./(2*((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))^2))))+abs(meansarray(4)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_8_patient(patnum))/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_8_patient(patnum))))*mu_input_mismatch)).^2./(2*((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))^2))))+abs(meansarray(5)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_16_patient(patnum))/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_input_match)).^2./(2*((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))^2))))+abs(meansarray(6)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))*exp(-(x-(((100/vocode_report_16_patient(patnum))/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_pred + (x(1)/(x(1)+(100/vocode_report_16_patient(patnum))))*mu_input_mismatch)).^2./(2*((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))^2)))))

abs(meansarray(1)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))
abs(meansarray(2)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))
abs(meansarray(3)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))
abs(meansarray(4)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))
abs(meansarray(5)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))
abs(meansarray(6)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))

(abs(meansarray(1)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))+abs(meansarray(2)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))+abs(meansarray(3)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))+abs(meansarray(4)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))+abs(meansarray(5)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))+abs(meansarray(6)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi))))))

(abs(meansarray(1)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))+abs(meansarray(2)-((1/(((1/x(1) + 1/(100/vocode_report_4_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))+abs(meansarray(3)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))+abs(meansarray(4)-((1/(((1/x(1) + 1/(100/vocode_report_8_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi)))))+abs(meansarray(5)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_match))*sqrt(2*pi)))))+abs(meansarray(6)-((1/(((1/x(1) + 1/(100/vocode_report_16_patient(patnum)))^-1+x(2)*abs(mu_pred-mu_input_mismatch))*sqrt(2*pi))))))